### ISSUE TITLE
Why does rim add an R package library folder?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/rim#43]
i.e. it created `/Users/davis/Library/R/x86_64/4.1/library` when I ran `rim add release`.

Is it just good practice to keep your CRAN R package library separate from the base R packages? I've never used a separate library before.

I guess R knew to find it there because of this?

```r
> Sys.getenv("R_LIBS_USER")
[1] "~/Library/R/x86_64/4.1/library"
```

```r
> .libPaths()
[1] "/Users/davis/Library/R/x86_64/4.1/library"                     
[2] "/Library/Frameworks/R.framework/Versions/4.1/Resources/library"
```

**Comment by gaborcsardi** [comment]
Yes, it is just better practice to keep your packages in a user library. That makes it easier to create an isolated library, which is otherwise hard, because `.Library` is always on the library path. E.g. revdepcheck cannot create isolated libraries for the `old` and `new` checks if you have non-base packages in `.Library`. 

It also makes it easier to remove and re-add R version without losing your library.

**Comment by DavisVaughan** [comment]
Makes sense!
